################
### Language ###
################
language: java

###########
### JDK ###
###########
jdk:
  - oraclejdk11

###############
### Caching ###
###############
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

#############
### Sonar ###
#############
addons:
  sonarcloud:
    organization: "mysteryworlds"
    token:
      secure: b1QCqukyPPRJrL1XUGI/Fl7aNN8+7DF41Sl9RZZCQTN4VY8p6Yd16UelmLVJbpkVwOkFwMvgounRRLREpC18XO4+QK2p8G6pPVsgT3GWK7lUA4MRClmFyQD+67W4S+m30iJzvjn8qb6ieHAFix10ErA3PqhLi9/rUk99ARcvx9ppT+t/vGLaJOEfIJJLwYCqReTwdc1uTqKaZTy3MpxBAJBi7NyXgE6h93EzyXQRWxFyg6wVeecFOMHlGTXDDD/ilsm4IpToEosk9zdkTJrHH2tCeZNyxu01FN44n7bT6p2vWAAHPlWnfcA6I2hBkHYjerJ0C4vM0coO6E/ycR9qCJ+3qBSLBt+kvv4vMv/HXFR/FICPuxAsoGN1cycosxk1ZAzTuaQw0rgk6enNEeq1l4fRa3arQenhOHubL21c6MOBw2751ZUulxE/QSoNjLe7BjWJDwJQ9DDHkSpknu+JCWkleN4bZb6+H8sT+7tLqH0ODOic7qx0mgckyV+evOFJO0vM+2q7ITfqMR9akNtRsSjYKaGDPuF9dWwRpTt7kjVRTkzolwMMGJWingNtqRNkJqN7PNYBXPM1NIQsOHLd7QEE78Biqx1NKAED0QjafZz64i7EOgwrwxItTKxlPMig1b8qLzcNtoY8SAnk/0f7K0xUtwPxaIAi6pnJMQpi8LY=

#####################
### Notifications ###
#####################
notifications:
  email: false

####################
### Build script ###
####################
script:
  - mvn clean install
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=mysteryworlds_chloe

##################
### Deployment ###
##################
deploy:
  provider: script
  script: mvn deploy --settings deploy/maven-settings.xml
  on:
    branch: master
    tags: true

env:
  global:
    - NEXUS_USERNAME=deploy
    - secure: "FvBs5nwE1ot5fx1BZU7jG0r7ajLbvPuK3KM3qzksIw0Qcvl3OTk5tS55dXIATrO1eKsy95WVsJyu7i6YY2p47G+BHjB6e0uRtRmSsIcfLAlkx6YfzcxeZLB5jx9SLSiMkXGLpkLjYr2RVGdWT8t1KjHkwoaaMlcxX3qFJ/I8whKtFx9y+l3BUnwRHDioAqdVboDSLd4Et5nIDnj9jp8Q5HR0P87gSdCaKhO+Wp819kKput6DtjTqk4ulVfIRSpc+VRKn7X4azNf30e9rkizrCCcWg+3JOUw1mwMCrSb7ZHFGj/3JO3IuO8McycmsQKs0FWtUaMFdxwVRGM5Jszww77AR+f89L6tTJ5vdvvIIUQzQD+4Qza/fmgkrylLsd9KEezoM1oWu4y91+e0W0gCuXnvaC0hi0eDXr1zN8XGMLg4mevKJnEpbCizlmybDmGrqllrHdCPVZqRdl2LWZVcDJY+5+fpXVOH8AF/rvUEvfAp8YK/XgJ2S+wQvEIJR/GhE6sOGn9/w9NJnpwTTf5YXqiElK9ELsZ73Q4pjNNy/uyzrbaizLmtF8UY+3Csruq6JjpsaKTjAN4aq8os/J+UhNacR0XPWaJ+OFd2T31404apK3cPmxCWoryACVUp1wVBPI4Sw8R/dqEmHxO1TcD3vfr0AFNWavv/gdErX2M/bH88="
